### ISSUE TITLE
Use io-uring kernel polling in kernel version >= 5.11

### ISSUE THREAD

**Issue by ShuochengWang** [occlum/ngo#49]
Now we use `start_enter_syscall_thread` to walkaround the limition of io-uring, see details in https://github.com/axboe/liburing/issues/273

``` Rust
    pub unsafe fn start_enter_syscall_thread(fd: c_int) {
        use std::thread;
        println!("start_enter_syscall_thread");
        thread::spawn(move || loop {
            syscall(
                __NR_io_uring_enter as c_long,
                fd as c_long,
                1,
                0,
                0,
                std::ptr::null() as *const c_void,
                0,
            );
        });
    }
```

And the arguments of __NR_io_uring_enter is:
`io_uring_enter(fd, to_submit, min_complete, flags, sig, siglen)`

- We should use io-uring kernel polling instead of `start_enter_syscall_thread` in 5.11+ kernel version
- We should set the `min_complete` to 1 in `start_enter_syscall_thread` to save power (not tested yet)

**Comment by tatetian** [comment]
This issue is replaced by #255 .
